#!/bin/sh
lock() {
    i3lock -t -i ~/.i3/image.png #-p win
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        pm-suspend-hybrid
        ;;
    hibernate)
        pm-hibernate
        ;;
    reboot)
        reboot
        ;;
    shutdown)
        shutdown
        ;;
    *)
        echo "Usage $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
